---
# roles/downloader/tasks/main.yml

- name: Install free download manager on {{ ansible_distribution }}
  tags: install,downloader
  import_tasks: install_freedownloadmanager.yml
  when: ansible_distribution in linux_os
