---
# roles/password-manager/tasks/install_buttercup.yml

- name: Download Buttercup AppImage
  get_url:
    url: "https://github.com/buttercup/buttercup-desktop/releases/download/v{{ buttercup.version }}/Buttercup-linux-x86_64.AppImage"
    dest: /opt/buttercup/Buttercup-{{ buttercup.version }}-x86_64.AppImage
    mode: "0755"
  become: true

- name: Make Buttercup AppImage executable
  ansible.builtin.file:
    path: /opt/buttercup/Buttercup-{{ buttercup.version }}-x86_64.AppImage
    mode: "u+x"
  become: true

- name: Create a symbolic link to the Buttercup AppImage
  file:
    src: "/opt/buttercup/Buttercup-{{ buttercup.version }}-x86_64.AppImage"
    dest: "/usr/local/bin/buttercup"
    state: link
