---
# file: setup-workspace.yml

- hosts: workspace
  roles:
    - dotfiles
    - pnpm
    - brew
    - mosh
    # - git
    # - eslint
    # - write_good
    # - prettier
    - rust
    - nvim
    # - kool
    - oh-my-fish
