---
# roles/notes/tasks/install_obsidian.yml

- name: Download Obsidian .deb package
  ansible.builtin.get_url:
    url: "https://github.com/obsidianmd/obsidian-releases/releases/download/v{{ obsidian.version }}/obsidian_{{ obsidian.version }}_amd64.deb"
    dest: "/tmp/obsidian_{{ obsidian.version }}_amd64.deb"
    mode: "0644"

- name: Install Obsidian .deb package
  ansible.builtin.apt:
    deb: "/tmp/obsidian_{{ obsidian.version }}_amd64.deb"
    state: present
  become: true
