---
# roles/dotfiles/tasks/configure_symlink.yml
- name: Get list all files 
  find:
    paths: "{{ symlinks.path_files }}"
    recurse: no
    hidden: yes
    file_type: file
    excludes: "{{ symlinks.exclude_files }}"
  register: files

- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  with_items: "{{ create.folders }}"

- name: Create a file symbolic link
  file:
    src: "{{ item.path }}"
    dest: "{{ item.path | 
      replace(lookup('ansible.builtin.env', 'HOME'), '~') | 
      replace('~/dotfiles', '~') | 
      replace('~/local-env', '~') }}"
    state: link
  with_items: "{{ files.files }}"

- name: Remove existing symbolic link folder
  file:
    path: "{{ item | replace('~/dotfiles', '~') }}"
    state: absent
  with_items: " {{ symlinks.folders }}"

- name: Create a folder symbolic link
  file:
    src: "{{ item }}"
    dest: "{{ item | replace('~/dotfiles', '~') }}"
    state: link
  with_items: " {{ symlinks.folders }}"
