---
# roles/dotfiles/tasks/configure_symlink.yml

- name: Get list all files
  find:
    paths: "{{ symlinks.path_files }}"
    recurse: no
    hidden: yes
    file_type: file
    excludes: "{{ symlinks.exclude_files }}"
  register: found_files

- name: Create file symlinks from ~/dotfiles to ~/
  include_role:
    name: common
    tasks_from: create_file_symlink.yml
  vars:
    files: "{{ found_files.files | map(attribute='path') }}"
    replace_with: "~"
    patterns: "{{ symlinks.replace_patterns }}"

- name: Create folder symlinks from ~/dotfiles to ~/
  include_role:
    name: common
    tasks_from: create_folder_symlink.yml
  vars:
    folders: "{{ symlinks.folders }}"
    replace_with: "~"
    patterns: "{{ symlinks.replace_patterns }}"
