---
# roles/dotfiles/tasks/main.yml

- name: Get list all files 
  find:
    paths: 
      - ~/dotfiles
      - ~/dotfiles/local-env
    recurse: no
    file_type: file
    excludes: 
      - '.git'
      - '.gitmodules'
      - 'readme.md'
  register: files

- name: Create a file symbolic link
  file:
    src: "{{ item }}"
    dest: "{{ item.path | 
      replace(lookup('ansible.builtin.env', 'HOME'), '~') | 
      replace('~/dotfiles', '~') | 
      replace('~/local-env', '~') }}"
    state: link
  with_items: "{{ files.files }}"

- name: Debug 
  debug:
    msg: "{{ files.files }}"

- name: Create a folder symbolic link
  file:
    src: "{{ item }}"
    dest: "{{ item | replace('~/dotfiles', '~/') }}"
    state: link
  with_items: 
    - ~/dotfiles/.config/fish
    - ~/dotfiles/.config/lvim
    - ~/dotfiles/.local/share/pnpm
