---
# roles/oh-my-fish/tasks/configure_fish.yml

- name: Configure PATH for fish shell
  command: fish -c "fish_add_path /home/hao/.local/bin/
    /home/linuxbrew/.linuxbrew/bin/"
  environment:
    PATH: "/home/linuxbrew/.linuxbrew/bin/:{{ ansible_env.PATH }}"
  register: result
  changed_when: result.rc == 2
  failed_when: result.rc == 2

- name: Remove Fish Greetings
  command: fish -c "set -U fish_greeting"
  environment:
    PATH: "/home/linuxbrew/.linuxbrew/bin/:{{ ansible_env.PATH }}"
  register: result
  changed_when: result.rc == 2

- name: Download os icon from {{ oh_my_fish.icon_url | regex_replace('\\s') }}
    to /usr/local/bin/os-icon
  ansible.builtin.get_url:
    url: "{{ oh_my_fish.icon_url | regex_replace('\\s') }}"
    dest: /usr/local/bin/os-icon
  become: yes

- name: Make the binary executable
  file:
    dest: /usr/local/bin/os-icon
    mode: a+x
  become: yes
