---
# roles/brew/vars/main.yml
# don't change filename to vars/install.yml (not loaded)

linuxbrew: /home/linuxbrew/.linuxbrew/bin
bashrc: $HOME/.bashrc
install: 
  url: https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh
