---
# roles/brew/tasks/install.yml

- name: Check if linux brew already installed on {{ brew.dir }}
  stat:
    path: "{{ brew.dir }}/brew"
  register: brew_check

- name: install apt build-essential
  become: yes
  apt:
    name: build-essential
    state: absent
  when: not brew_check.stat.exists

- name: Add current user as sudoers
  become: true
  community.general.sudoers:
    name: add-current-user-sudoers
    state: present
    user: "{{ lookup('ansible.builtin.env', 'USER') }}"
    commands: ALL
    nopassword: true

- name: Install brew package
  include_role:
    name: common
    tasks_from: install_package_remote_shell_script.yml
  vars:
    package:
      name: "brew"
      url: "{{ brew.url }}"
      register_env_path: "{{ brew.env }}"
      dir: "{{ brew.dir }}"
      shell: /bin/bash /tmp/brew
      bin: "brew"
      check_version: true
      env:
        PATH: "{{ brew.dir }}:{{ ansible_env.PATH }}"
        # Non Interactive mode
        CI: 1
  when: not brew_check.stat.exists
