---
# roles/brew/tasks/install.yml

- name: check if linux brew already installed on {{ brew.folder }}
  stat:
    path: "{{ brew.folder }}/brew"
  register: brew_check

- name: install apt build-essential
  become: yes
  apt:
    name: build-essential
    state: absent
  when: not brew_check.stat.exists

- name: install linux brew
  ansible.builtin.shell: /bin/bash -c "$(curl -fsSL {{ brew.url }})"
  when: not brew_check.stat.exists

- name: register brew binary files to path
  lineinfile:
    state: present
    dest: "{{ brew.env }}"
    line: 'export PATH="{{ brew.folder }}:$PATH"'
    insertafter: EOF
  environment:
    PATH: "{{ brew.folder }}:{{ ansible_env.PATH }}"
  when: brew_check.stat.exists

- name: check Brew is working fine
  command: brew --version
  environment:
    PATH: "{{ brew.folder }}:{{ ansible_env.PATH }}"
  register: result
  changed_when: result.rc == 2
