---
# roles/brew/tasks/install.yml

- name: Check if linux brew already installed on {{ brew.dir }}
  stat:
    path: "{{ brew.dir }}/brew"
  register: brew_check

- name: install apt build-essential
  become: yes
  apt:
    name: build-essential
    state: absent
  when: not brew_check.stat.exists

- name: Install brew package
  include_role:
    name: common
    tasks_from: install_package_remote_shell_script.yml
  vars:
    package:
      name: "brew"
      env: "{{ brew.env }}"
      dir: "{{ brew.dir }}"
      shell: /bin/bash -c "$(curl -fsSL {{ brew.url }})"
      check_version: true
      register_path: true
  when: not brew_check.stat.exists
