---
# roles/brew/tasks/main.yml

- name: check if linux brew already installed
  stat:
    path: /home/linuxbrew/.linuxbrew/bin/brew
  register: brew

- name: install apt build-essential
  become: yes
  apt:
    name: build-essential
    state: absent
  when: not brew.stat.exists

- name: install linux brew
  ansible.builtin.shell: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  when: not brew.stat.exists

- name: register brew binary files to path
  lineinfile:
    dest: $HOME/.bashrc
    line: 'export PATH="/home/linuxbrew/.linuxbrew/bin:$PATH"'
    insertafter: EOF
  when: brew.stat.exists

- name: source bashrc to make sure brew path exported in current terminal session
  ansible.builtin.shell: 'source $HOME/.bashrc'
  ignore_errors: yes
  when: brew.stat.exists

- name: check Brew is working fine
  ansible.builtin.shell: 'brew doctor'
  when: brew.stat.exists
