---
# roles/brew/tasks/main.yml

- name: Install and setup linuxbrew on Ubuntu
  import_tasks: install.yml
  when: ansible_distribution == "Ubuntu"

- name: Install required package with linuxbrew on Ubuntu
  import_tasks: package.yml
  when: ansible_distribution == "Ubuntu"
