---
# roles/brew/tasks/package.yml

- name: Installing required package with linuxbrew
  environment:
    PATH: "{{ brew.folder }}:{{ ansible_env.PATH }}"
  community.general.homebrew:
    name: "{{ brew.packages }}"
    state: latest
    update_homebrew: yes

- name: Check Installed packages
  debug:
    msg: "{{ item }}"
  loop: "{{ brew.packages }}"
