---
# roles/git/tasks/main.yml

- name: configure git global configurations
  tags: configure,git,global
  import_tasks: configure.yml

- name: install commitizen
  tags: install,commitizen
  import_tasks: install-commitizen.yml
