---
# roles/dotfiles/tasks/configure_symlink.yml

- name: Create file symlinks from ~/dotfiles to ~/
  include_role:
    name: common
    tasks_from: create_file_symlink.yml
  vars:
    files:
      - "{{ pnpm.global.file }}"
    replace_with: "~"
    patterns: "{{ pnpm.global.replace_patterns }}"
