---
# roles/pnpm/tasks/install.yml

- name: Check pnpm binary exists {{ pnpm.dir }}/{{ pnpm.name }}
  stat:
    path: "{{ pnpm.dir }}/{{ pnpm.name }}"
  register: check_file

- name: Install pnpm package
  include_role:
    name: common
    tasks_from: install_package_remote_shell_script.yml
  vars:
    package:
      name: "{{ pnpm.name }}"
      url: "{{ pnpm.url | regex_replace('\\s') }}"
      dir: "{{ pnpm.dir }}"
      shell: sh /tmp/pnpm
      check_version: true
      env:
        PATH: "{{ pnpm.dir }}:{{ ansible_env.PATH }}"
        PNPM_HOME: "{{ pnpm.dir }}"
  when: not check_file.stat.exists

- name: Check pnpm version
  command: "pnpm --version"
  register: result
  environment:
    PATH: "{{ pnpm.dir }}:{{ lookup('ansible.builtin.env', 'PATH') }}"
    PNPM_HOME: "{{ pnpm.dir }}"
  changed_when: result.rc == 2
  when: check_file.stat.exists

- name: Configure global package symlink
  tags: install,pnpm
  import_tasks: configure_symlink.yml
