---
# roles/pnpm/tasks/install_global_package.yml

# - name: Install global package
#   shell: ". ~/.profile; pnpm install -g"
#   register: result
#   changed_when: result.rc == 2
- name: Run shell script to install global package
  script: 
    cmd: install_global_package.sh 
  register: result

- name: Debug shell script
  debug:
    msg: "{{ result.stdout_lines }}"
