---
# roles/pnpm/tasks/main.yml

- name: Install global package
  command: pnpm install -g
  environment:
    PATH: "{{ pnpm.dir }}:{{ lookup('ansible.builtin.env', 'PATH') }}"
    PNPM_HOME: "{{ pnpm.dir }}"
  register: result
  changed_when: result.rc == 2
