---
# roles/mosh/tasks/main.yml

- name: check if mosh already installed
  stat:
    path: /usr/bin/mosh
  register: mosh

- name: install mosh
  become: yes
  apt:
    name: mosh
  when: not mosh.stat.exists

- name: check mosh version
  command: mosh --version
  register: result
  changed_when: result.rc == 2
