---
# roles/kool/tasks/main.yml

- name: Install and setup kool on {{ ansible_distribution }}
  tags: install,kool
  become: yes
  import_tasks: install.yml
  when: ansible_distribution in linux_os

- name: Configure kool
  become: yes
  import_tasks: configure_kool.yml
