---
# roles/common/tasks/install_apt_package.yml

- name: Check if package {{ package.name }} already installed
  stat:
    path: "{{ package.bin_dir }}/{{ package.name }}"
  register: package_check

- name: Install package {{ package.name }}
  become: yes
  apt:
    name: "{{ package.name }}"
  when: not package_check.stat.exists

- name: Check package {{ package.name }} version
  command: "{{ package.name }} --version"
  register: result
  changed_when: result.rc == 2
  when: package.check_version | default(false)
