---
# roles/nvim/tasks/main.yml

- name: Check if directory nvim exist
  stat:
    path: "{{ config.dir }}"
  register: nvim_dir

- name: Create directory {{ config.dir }}
  file:
    path: "{{ config.dir }}"
    state: directory
    mode: 0755
  when: not nvim_dir.stat.exists
