---
# roles/nvim/tasks/main.yml

- name: Configure Neovim
  tags: configure,nvim
  import_tasks: configure_nvim.yml
  vars:
    config: "{{ nvim }}"

- name: Install lvim
  tags: configure,lvim
  import_tasks: install_lvim.yml
