---
# roles/nvim/tasks/main.yml

- name: Configure Neovim
  tags: configure,nvim
  import_tasks: configure_nvim.yml
  vars:
    config: "{{ nvim }}"

# - name: Install lvim
#   tags: install,lvim
#   import_tasks: install_lvim.yml

- name: Install astronvim
  tags: install, astronvim
  import_tasks: install_astronvim.yml
